CSEdgeOfficial/learn.csedge.courses

- index.html
- posts/azure/How-to-Create-an-Azure-Account.html
- posts/github/How-to-Apply-for-GitHub-Student-Developer-Pack.html
- posts/github/How-to-Make-Pull-Requests-on-GitHub.html
- posts/github/how-to-create-github-account.html
- posts/java/how-to-install-jdk.html
- posts/linkedin/creating-professional-linkedin-account.html
- posts/technology/how-to-create-JSON-Server.html
Added home page link to the logo text in all html files by providing correct path of the index.html(home page) in all the 
html filesl.
> Added home page link to the logo text in all html files

- index.html
- posts/script.js
ISSUE  #32 
Search Bar Results Changes
> style: changed search bar results style. issue #32

- posts/azure/How-to-Create-an-Azure-Account.html
- posts/github/How-to-Apply-for-GitHub-Student-Developer-Pack.html
- posts/github/How-to-Make-Pull-Requests-on-GitHub.html
- posts/github/how-to-create-github-account.html
- posts/linkedin/creating-professional-linkedin-account.html
- posts/styles.css
- Fixed missing blog titles
- Fixed the position of the blog title
Issue #50 is resolved
> Blog title position is fixed

- home.html
Aniamations added using AOS.js
issue #20 solved
https://github.com/CSEdgeOfficial/learn.csedge.courses/assets/125277258/ca1cadc6-f361-4556-96e7-96c1929e79d1
> animations added

- home.html
- navbar.css
Added suitable icons for different sections in the navbar 
By default the icons were coming white so I changed the color to black for better visibility
PFA the screenshot
> Solved issue #142- Adding suitable icons . 

- index.html
Added suitable icons on the navbar for the website.
>  Issue Number :#142  Added suitable icons

- home.css
- navbar.css
This pull request proposes improvements to the UI of the navigation bar using CSS.
Changes Made:
Fixed navbar at the top
Added hover effects to enhance user interaction
Fixes issue #7 
Testing: Manually tested the changes on various screen sizes.
Please review the implemented changes and provide feedback. I welcome your suggestions for further improvement.
> fixed navbar at the top with some hover effects

- csedge.courses/Resources.html
> Videos section

- csedge.courses/Internships/Full-Stack-Development.html
- csedge.courses/Internships/Java.html
- csedge.courses/Internships/Web-Development.html
- csedge.courses/Internships/python.html
- csedge.courses/Resources.html
- csedge.courses/about.html
- csedge.courses/index.html
- csedge.courses/internship.html
- csedge.courses/verify-id.html
- index.html
Fixed issue #177 
- Updated the footer to display the current year dynamically using JavaScript.
- Replaced the hardcoded year with a <script> tag that inserts the current year.
- Ensures the footer year is always up-to-date without manual changes.
> Add dynamic current year to footer

- home.css
- home.html
- index.html
- navbar.css
i improve the ui of navbar of the home page 
please accept the pr and level it gsoc 24
> improve the ui of navbar

- home.html
I have made the changes as stated in the issue #193 .
Hence fixed the issue #193. 
Thank you :)
> Fixed issue #193

- index.html
- posts/github/How-to-setup-your-github-local-repository.html
Issue: #207 
I wrote a blog post on how to set up a local GitHub repository with detailed steps to follow. This blog post will be helpful for the new open-source contributors
> [Technical Writing] Blog post on how to set up your local GitHub repository.

- csedge.courses/privacypolicy.css
- csedge.courses/privacypolicy.html
- index.html
Added Privacy Policy Page for the website.
- Documentation Update
-  I have performed a self-review of my code
-  I have read and followed the Contribution Guidelines.
-  I have tested the changes thoroughly before submitting this pull request.
> Added Privacy Policy page

- home.css
- home.html
[Please include a brief description of the changes or features added]
> Home page made responsive, Improve Navbar

- css/styles.css
- index.html
Hey @CSEdgeOff 
Fixed #222 
[Please include a brief description of the changes or features added]
There were unnecessary spaces which I have removed.
- [x ] Bug fix
Before:
After:
Before:
After:
- [x ] I have performed a self-review of my code
- [ x] I have read and followed the Contribution Guidelines.
- [ x] I have tested the changes thoroughly before submitting this pull request.
- [ x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [ x] I have commented my code, particularly in hard-to-understand areas.
> Removed unecessary spaces

- .github/workflows/autocomment-issue.yml
- .github/workflows/autocomment-pr-raise.yml
Removed links
@Durgesh-Vaigandla please review this PR and merge it
> Removed links

- .idea/.gitignore
- .idea/learn.csedge.courses.iml
- .idea/modules.xml
- .idea/vcs.xml
- home.html
I have made the required corrections regarding the grammars and punctuations in the project so as to make it look more professional.
> Grammar, Punctuation and case sensitive errors fixed

- home.css
- home.html
#258
Added new FAQs section and updated CSS
- Documentation update
-  I have performed a self-review of my code
-  I have read and followed the Contribution Guidelines.
-  I have tested the changes thoroughly before submitting this pull request.
-  I have provided relevant issue numbers, screenshots ,after making the changes.
> Added new FAQs section and updated CSS

- csedge.courses/Resources.html
- Done #255 
- Added hover effect to the cards 
> updated content-card

- css/styles.css
- index.html
> Added margin to heading

- csedge.courses/about.html
- csedge.courses/index.css
I changed text-align to justify large displays .
And did text-align center for small devices .
> Fix the Alignment of Text in About Section

- index.html
> Make changes in the Next and  Previous Section

- home.html
BUG:Navrbar Home,Contact Link , Scorll Behaviour #319 
so previously in navbar link of contact and home button was not given 
so user can not go contact section by  navbar
and home link was not given so user can not reach top by navbar he has to either scroll or use top button 
i have added both links properly in this PR 
No need of Screenshot , just link added
- [x I have commented my code, particularly in hard-to-understand areas.
it was easy issue but feel good to work eith you 
Thank you
> contact,home  link fixed

- index.html
I solve issue #334 to solved the navbar align issue in desktop mode.
Before make change it having two contact us button then it make fault of website.
So I make change it look good.
- [ #334 ] Bug fix
Before change will happen:
NOW navbar is 👍
> Make Navbar properly aligned in DESKTOP mode.

- home.html
Reverts CSEdgeOfficial/learn.csedge.courses#372
> Revert "Replaced Contact section at Home page with the Form"

- chatbox.css
- chatbox.js
- home.css
- home.html
- navbar.css
Fixes #343 
I have added a chatbox that displays questions on saying hi. And on clicking on questions, answers are displayed.
Chatbox is responisve for all mobile/tablet/pc devices. And doesn't interfere with other elements of the site.
> Fixes #343

- css/main.css
- home.css
- home.html
Changed Footer -
**BEFORE**
**AFTER**
> Changed Footer

- index.html
#431
In Navbar section there was no hover effect. I add hover effect in existing html file. @CSEdgeOfficial
Please merge this little update in your main project under gssoc'24 and level  this PR.
Before Video -
https://github.com/CSEdgeOfficial/learn.csedge.courses/assets/136844498/b674e5dd-1105-4d5e-9937-1327cbfddcd8
After hover effect -
https://github.com/CSEdgeOfficial/learn.csedge.courses/assets/136844498/1a5a1095-5e5a-427f-9132-e16994cc2679
#431  
Description -
In Navbar section there is no hover effect.
Please assign me this task I'll add this effect with attractive color effect.
#437 
Footer section CSS style -
Before -
https://github.com/CSEdgeOfficial/learn.csedge.courses/assets/136844498/f668721e-02cd-4088-bff1-c507fbbe59c4
After adding Social media - …
> [Feature] Navbar sections buttons added hover effect.

- css/styles.css
- index.html
after click on hamburger dialog open but that icon needs to replace with cross icon instead of hamburger #435
None
Now cross icon comes up one dialog open after click on hamburger
> after click on hamburger dialog open but that icon needs to replace with cross icon instead of hamburger #435

- home.css
- home.html
- index.html
- posts/docker/Getting-Started-with-Docker.html
- posts/master-docker.html
- posts/master-github.html
#35  #320 solved these issues
adde Introduction to Docker: Getting Started with Containerization when we navigate to page1
> Solved the pagination issue

- index.html
[Please include a brief description of the changes or features added]
> Fixed Changes

- csedge.courses/index.css
Fixed issue : #300 
@CSEdgeOff  @Durgesh-Vaigandla  Please review and merge this PR.
Added Hover Effect in Footer Links
> Added Hover Effect in Footer Links

- index.html
Added subscribe to newsletter
Added subscribe to newsletter
closes #472 
- [x ] Feature enhancement
- [x ] I have performed a self-review of my code
- [ x] I have read and followed the Contribution Guidelines.
- [x ] I have tested the changes thoroughly before submitting this pull request.
- [ x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x ] I have commented my code, particularly in hard-to-understand areas.
> Added subscribe to newsletter

- index.html
Added Hover Effect for the subscribe to newsletter button
closes #474 
- [ x] Feature enhancement
- [ x] I have performed a self-review of my code
- [x ] I have read and followed the Contribution Guidelines.
- [x ] I have tested the changes thoroughly before submitting this pull request.
- [x ] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [ x] I have commented my code, particularly in hard-to-understand areas.
> Added Hover Effect for the subscribe to newsletter button

- index.html
#514 #549 
@Durgesh-Vaigandla 
[Please include a brief description of the changes or features added]
> bottom to top functionality added
